### ISSUE TITLE
"I don't know how to apply that word here"

### ISSUE THREAD

**Issue by drefrome** [troglobit/adventure#1]
I'm very excited that you've done this port! I didn't find the commands to build in the readmes, so I made my best guess as to how to build it:

```
./autogen
./configure
make
```

(were there instructions I missed?) I started the game by running `src/advent`, but pretty quickly I ran into problems with it not recognizing commands. "take lamp" etc worked, but "follow stream" yields "I don't know how to apply that word here." (and no directions work to get me to the grate). Looks like either a problem with my compile or a bug in the program?

**Comment by troglobit** [comment]
Hi, glad you like it! :)

You have indeed found a regression.  I just tested an older commit and there 'follow stream' works as it should.  I'll see what I can do about tracking this down.  Also, another thing ... from back in my day on CP/M I distinctly remember starting the game outside the house, maybe you can provide some insight there? (The older commit also starts inside the house, but online docs and walkthroughs seem to start outside.)

I'll make sure to update the README with build instructions.  (You should only need autogen.sh when building from git)

**Comment by troglobit** [comment]
There, found and fixed! Thank you for taking the time to report this :)

**Comment by drefrome** [comment]
Very welcome and thanks for responding! Sorry for not replying sooner, but yes, the other versions I found do start you outside the building as you recall, but I'm guessing that's also working as expected now.  :)

**Comment by troglobit** [comment]
No problem. Yup, fixed that too while I was at it :)
